package ru.megains.farlandsOld.loaders;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.g2d.Sprite;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;

import java.util.HashMap;

public class ItemsAtlasLoader {
    private static TextureAtlas materialAtlass;
    private static TextureAtlas equipedAtlas;
    private static TextureAtlas bookAtlas;
    private static HashMap<Integer, Sprite> items = new HashMap();

    public ItemsAtlasLoader() {
    }

    public static void load() {
        materialAtlass = new TextureAtlas(Gdx.files.internal("items/materials.pack"));
        equipedAtlas = new TextureAtlas(Gdx.files.internal("items/eqiped_items.pack"));
        bookAtlas = new TextureAtlas(Gdx.files.internal("items/books.pack"));
        Sprite item = new Sprite(bookAtlas.findRegion("book_mine_wood1"));
        items.put(1001, item);
        item = new Sprite(bookAtlas.findRegion("book_mine_skin1"));
        items.put(1007, item);
        item = new Sprite(bookAtlas.findRegion("book_mine1"));
        items.put(1006, item);
        item = new Sprite(bookAtlas.findRegion("book_fight1"));
        items.put(1009, item);
        item = new Sprite(bookAtlas.findRegion("book_treasure1"));
        items.put(1010, item);
        item = new Sprite(equipedAtlas.findRegion("mine_gather_x1"));
        items.put(305, item);
        item = new Sprite(equipedAtlas.findRegion("mine_gather_x2"));
        items.put(306, item);
        item = new Sprite(equipedAtlas.findRegion("mine_gather_x3"));
        items.put(307, item);
        item = new Sprite(equipedAtlas.findRegion("mine_gather_x4"));
        items.put(309, item);
        item = new Sprite(bookAtlas.findRegion("book_mine_gather1"));
        items.put(1008, item);
        item = new Sprite(bookAtlas.findRegion("scroll_healing"));
        items.put(1002, item);
        item = new Sprite(bookAtlas.findRegion("scroll_energy"));
        items.put(1003, item);
        item = new Sprite(bookAtlas.findRegion("scroll_magic1"));
        items.put(1004, item);
        item = new Sprite(bookAtlas.findRegion("scroll_magic2"));
        items.put(1005, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe1"));
        items.put(418, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe2"));
        items.put(419, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe3"));
        items.put(420, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe4"));
        items.put(421, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe5"));
        items.put(422, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe3"));
        items.put(420, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe_small1"));
        items.put(411, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe_small2"));
        items.put(412, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe_small3"));
        items.put(413, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe_small4"));
        items.put(414, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_axe_small5"));
        items.put(416, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_dagger1"));
        items.put(439, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_dagger2"));
        items.put(440, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_dagger3"));
        items.put(441, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_dagger4"));
        items.put(442, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_dagger5"));
        items.put(443, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_hammer1"));
        items.put(460, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_hammer2"));
        items.put(461, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_hammer3"));
        items.put(463, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_hammer4"));
        items.put(464, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_hammer5"));
        items.put(466, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_flail1"));
        items.put(453, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_flail2"));
        items.put(454, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_flail3"));
        items.put(455, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_flail4"));
        items.put(457, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_flail5"));
        items.put(458, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_long_sword1"));
        items.put(479, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_long_sword2"));
        items.put(480, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_long_sword3"));
        items.put(481, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_long_sword4"));
        items.put(483, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_long_sword5"));
        items.put(485, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_short_sword1"));
        items.put(515, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_short_sword2"));
        items.put(516, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_short_sword3"));
        items.put(517, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_short_sword4"));
        items.put(518, item);
        item = new Sprite(equipedAtlas.findRegion("wpn_short_sword5"));
        items.put(519, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_mine1"));
        items.put(92, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_mine2"));
        items.put(93, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_mine3"));
        items.put(94, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_mine4"));
        items.put(96, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_mine5"));
        items.put(97, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_wood1"));
        items.put(115, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_wood2"));
        items.put(116, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_wood3"));
        items.put(117, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_wood4"));
        items.put(118, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_wood5"));
        items.put(119, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_hunter1"));
        items.put(80, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_hunter2"));
        items.put(81, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_hunter3"));
        items.put(82, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_hunter4"));
        items.put(83, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_hunter5"));
        items.put(84, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_banded1"));
        items.put(64, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_banded2"));
        items.put(65, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_banded3"));
        items.put(66, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_banded4"));
        items.put(67, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_banded5"));
        items.put(68, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_chain1"));
        items.put(69, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_chain2"));
        items.put(70, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_chain3"));
        items.put(71, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_chain4"));
        items.put(73, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_chain5"));
        items.put(74, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_leather1"));
        items.put(85, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_leather2"));
        items.put(86, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_leather3"));
        items.put(87, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_leather4"));
        items.put(88, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_leather5"));
        items.put(89, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_plate1"));
        items.put(99, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_plate2"));
        items.put(100, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_plate3"));
        items.put(101, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_plate4"));
        items.put(102, item);
        item = new Sprite(equipedAtlas.findRegion("amr_armor_plate5"));
        items.put(103, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots01"));
        items.put(120, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots02"));
        items.put(121, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots03"));
        items.put(123, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots04"));
        items.put(124, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots05"));
        items.put(125, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots06"));
        items.put(127, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots07"));
        items.put(128, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots08"));
        items.put(129, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots09"));
        items.put(131, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots10"));
        items.put(132, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots11"));
        items.put(133, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots12"));
        items.put(134, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots13"));
        items.put(135, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots14"));
        items.put(136, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots15"));
        items.put(137, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots16"));
        items.put(138, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots17"));
        items.put(139, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots18"));
        items.put(140, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots19"));
        items.put(141, item);
        item = new Sprite(equipedAtlas.findRegion("amr_boots20"));
        items.put(142, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers01"));
        items.put(152, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers02"));
        items.put(153, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers03"));
        items.put(154, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers04"));
        items.put(156, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers05"));
        items.put(157, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers06"));
        items.put(158, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers07"));
        items.put(159, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers08"));
        items.put(160, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers09"));
        items.put(161, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers10"));
        items.put(162, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers11"));
        items.put(163, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers12"));
        items.put(164, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers13"));
        items.put(165, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers14"));
        items.put(166, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers15"));
        items.put(167, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers16"));
        items.put(168, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers17"));
        items.put(169, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers18"));
        items.put(171, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers19"));
        items.put(172, item);
        item = new Sprite(equipedAtlas.findRegion("amr_bracers20"));
        items.put(173, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet01"));
        items.put(184, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet02"));
        items.put(185, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet03"));
        items.put(186, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet04"));
        items.put(187, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet05"));
        items.put(188, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet06"));
        items.put(189, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet07"));
        items.put(190, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet08"));
        items.put(191, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet09"));
        items.put(192, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet10"));
        items.put(193, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet11"));
        items.put(194, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet12"));
        items.put(195, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet13"));
        items.put(196, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet14"));
        items.put(197, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet15"));
        items.put(198, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet16"));
        items.put(199, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet17"));
        items.put(200, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet18"));
        items.put(201, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet19"));
        items.put(202, item);
        item = new Sprite(equipedAtlas.findRegion("amr_helmet20"));
        items.put(203, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_big1"));
        items.put(213, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_big2"));
        items.put(214, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_big3"));
        items.put(215, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_big4"));
        items.put(216, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_big5"));
        items.put(217, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_medium1"));
        items.put(222, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_medium2"));
        items.put(223, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_medium3"));
        items.put(225, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_medium4"));
        items.put(227, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_medium5"));
        items.put(228, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_small1"));
        items.put(229, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_small2"));
        items.put(230, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_small3"));
        items.put(231, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_small4"));
        items.put(232, item);
        item = new Sprite(equipedAtlas.findRegion("amr_shield_small5"));
        items.put(233, item);
        item = new Sprite(equipedAtlas.findRegion("necklace01"));
        items.put(341, item);
        item = new Sprite(equipedAtlas.findRegion("necklace02"));
        items.put(342, item);
        item = new Sprite(equipedAtlas.findRegion("necklace03"));
        items.put(343, item);
        item = new Sprite(equipedAtlas.findRegion("necklace04"));
        items.put(345, item);
        item = new Sprite(equipedAtlas.findRegion("necklace05"));
        items.put(346, item);
        item = new Sprite(equipedAtlas.findRegion("necklace06"));
        items.put(348, item);
        item = new Sprite(equipedAtlas.findRegion("necklace07"));
        items.put(349, item);
        item = new Sprite(equipedAtlas.findRegion("necklace08"));
        items.put(351, item);
        item = new Sprite(equipedAtlas.findRegion("necklace09"));
        items.put(352, item);
        item = new Sprite(equipedAtlas.findRegion("necklace10"));
        items.put(353, item);
        item = new Sprite(equipedAtlas.findRegion("necklace11"));
        items.put(354, item);
        item = new Sprite(equipedAtlas.findRegion("necklace12"));
        items.put(355, item);
        item = new Sprite(equipedAtlas.findRegion("necklace13"));
        items.put(356, item);
        item = new Sprite(equipedAtlas.findRegion("necklace14"));
        items.put(357, item);
        item = new Sprite(equipedAtlas.findRegion("necklace15"));
        items.put(358, item);
        item = new Sprite(equipedAtlas.findRegion("necklace16"));
        items.put(359, item);
        item = new Sprite(equipedAtlas.findRegion("necklace17"));
        items.put(360, item);
        item = new Sprite(equipedAtlas.findRegion("necklace18"));
        items.put(361, item);
        item = new Sprite(equipedAtlas.findRegion("necklace19"));
        items.put(362, item);
        item = new Sprite(equipedAtlas.findRegion("necklace20"));
        items.put(363, item);
        item = new Sprite(equipedAtlas.findRegion("ring1"));
        items.put(374, item);
        item = new Sprite(equipedAtlas.findRegion("ring01"));
        items.put(373, item);
        item = new Sprite(equipedAtlas.findRegion("ring02"));
        items.put(375, item);
        item = new Sprite(equipedAtlas.findRegion("ring03"));
        items.put(376, item);
        item = new Sprite(equipedAtlas.findRegion("ring04"));
        items.put(377, item);
        item = new Sprite(equipedAtlas.findRegion("ring05"));
        items.put(378, item);
        item = new Sprite(equipedAtlas.findRegion("ring06"));
        items.put(379, item);
        item = new Sprite(equipedAtlas.findRegion("ring07"));
        items.put(380, item);
        item = new Sprite(equipedAtlas.findRegion("ring08"));
        items.put(381, item);
        item = new Sprite(equipedAtlas.findRegion("ring09"));
        items.put(382, item);
        item = new Sprite(equipedAtlas.findRegion("ring10"));
        items.put(383, item);
        item = new Sprite(equipedAtlas.findRegion("ring11"));
        items.put(384, item);
        item = new Sprite(equipedAtlas.findRegion("ring12"));
        items.put(385, item);
        item = new Sprite(equipedAtlas.findRegion("ring13"));
        items.put(387, item);
        item = new Sprite(equipedAtlas.findRegion("ring14"));
        items.put(389, item);
        item = new Sprite(equipedAtlas.findRegion("ring15"));
        items.put(390, item);
        item = new Sprite(equipedAtlas.findRegion("ring16"));
        items.put(392, item);
        item = new Sprite(equipedAtlas.findRegion("ring17"));
        items.put(393, item);
        item = new Sprite(equipedAtlas.findRegion("ring18"));
        items.put(394, item);
        item = new Sprite(equipedAtlas.findRegion("ring19"));
        items.put(395, item);
        item = new Sprite(equipedAtlas.findRegion("ring20"));
        items.put(396, item);
        item = new Sprite(equipedAtlas.findRegion("ring25"));
        items.put(402, item);
        item = new Sprite(equipedAtlas.findRegion("earring01"));
        items.put(272, item);
        item = new Sprite(equipedAtlas.findRegion("earring02"));
        items.put(273, item);
        item = new Sprite(equipedAtlas.findRegion("earring03"));
        items.put(274, item);
        item = new Sprite(equipedAtlas.findRegion("earring04"));
        items.put(275, item);
        item = new Sprite(equipedAtlas.findRegion("earring05"));
        items.put(276, item);
        item = new Sprite(equipedAtlas.findRegion("earring06"));
        items.put(277, item);
        item = new Sprite(equipedAtlas.findRegion("earring07"));
        items.put(279, item);
        item = new Sprite(equipedAtlas.findRegion("earring08"));
        items.put(280, item);
        item = new Sprite(equipedAtlas.findRegion("earring09"));
        items.put(282, item);
        item = new Sprite(equipedAtlas.findRegion("earring10"));
        items.put(283, item);
        item = new Sprite(equipedAtlas.findRegion("earring11"));
        items.put(284, item);
        item = new Sprite(equipedAtlas.findRegion("earring12"));
        items.put(285, item);
        item = new Sprite(equipedAtlas.findRegion("earring13"));
        items.put(286, item);
        item = new Sprite(equipedAtlas.findRegion("earring14"));
        items.put(287, item);
        item = new Sprite(equipedAtlas.findRegion("earring15"));
        items.put(288, item);
        item = new Sprite(equipedAtlas.findRegion("earring16"));
        items.put(290, item);
        item = new Sprite(equipedAtlas.findRegion("earring17"));
        items.put(291, item);
        item = new Sprite(equipedAtlas.findRegion("earring18"));
        items.put(292, item);
        item = new Sprite(equipedAtlas.findRegion("earring19"));
        items.put(293, item);
        item = new Sprite(equipedAtlas.findRegion("earring20"));
        items.put(294, item);
        item = new Sprite(equipedAtlas.findRegion("mine_hunter_bow1"));
        items.put(314, item);
        item = new Sprite(equipedAtlas.findRegion("mine_wood_axe1"));
        items.put(331, item);
        item = new Sprite(equipedAtlas.findRegion("mine_mine_pickaxe1"));
        items.put(322, item);
        item = new Sprite(equipedAtlas.findRegion("mine_hunter_bow2"));
        items.put(315, item);
        item = new Sprite(equipedAtlas.findRegion("mine_wood_axe2"));
        items.put(332, item);
        item = new Sprite(equipedAtlas.findRegion("mine_mine_pickaxe2"));
        items.put(323, item);
        item = new Sprite(equipedAtlas.findRegion("mine_hunter_bow3"));
        items.put(316, item);
        item = new Sprite(equipedAtlas.findRegion("mine_wood_axe3"));
        items.put(333, item);
        item = new Sprite(equipedAtlas.findRegion("mine_mine_pickaxe3"));
        items.put(324, item);
        item = new Sprite(equipedAtlas.findRegion("mine_hunter_bow4"));
        items.put(317, item);
        item = new Sprite(equipedAtlas.findRegion("mine_wood_axe4"));
        items.put(334, item);
        item = new Sprite(equipedAtlas.findRegion("mine_mine_pickaxe4"));
        items.put(325, item);
        item = new Sprite(equipedAtlas.findRegion("mine_hunter_bow5"));
        items.put(318, item);
        item = new Sprite(equipedAtlas.findRegion("mine_wood_axe5"));
        items.put(335, item);
        item = new Sprite(equipedAtlas.findRegion("mine_mine_pickaxe5"));
        items.put(327, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_amethyst"));
        items.put(18, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_amethyst1"));
        items.put(19, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_diamond"));
        items.put(20, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_diamond1"));
        items.put(21, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_emerald"));
        items.put(22, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_emerald1"));
        items.put(23, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_feerite"));
        items.put(24, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_feerite1"));
        items.put(25, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_onyx"));
        items.put(26, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_onyx1"));
        items.put(27, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_ruby"));
        items.put(28, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_ruby1"));
        items.put(29, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_topaz"));
        items.put(30, item);
        item = new Sprite(materialAtlass.findRegion("mat_gem_topaz1"));
        items.put(31, item);
        item = new Sprite(materialAtlass.findRegion("mat_metal_copper"));
        items.put(5, item);
        item = new Sprite(materialAtlass.findRegion("mat_metal_gold"));
        items.put(13, item);
        item = new Sprite(materialAtlass.findRegion("mat_metal_iron"));
        items.put(6, item);
        item = new Sprite(materialAtlass.findRegion("mat_metal_ironite"));
        items.put(4, item);
        item = new Sprite(materialAtlass.findRegion("mat_metal_rusty_iron"));
        items.put(1, item);
        item = new Sprite(materialAtlass.findRegion("mat_skin_boar"));
        items.put(11, item);
        item = new Sprite(materialAtlass.findRegion("mat_skin_deer"));
        items.put(10, item);
        item = new Sprite(materialAtlass.findRegion("mat_skin_rabbit"));
        items.put(3, item);
        item = new Sprite(materialAtlass.findRegion("mat_skin_varask"));
        items.put(14, item);
        item = new Sprite(materialAtlass.findRegion("mat_skin_wolf"));
        items.put(12, item);
        item = new Sprite(materialAtlass.findRegion("mat_wood_bad_topol"));
        items.put(2, item);
        item = new Sprite(materialAtlass.findRegion("mat_wood_dub"));
        items.put(9, item);
        item = new Sprite(materialAtlass.findRegion("mat_wood_osina"));
        items.put(7, item);
        item = new Sprite(materialAtlass.findRegion("mat_wood_yasen"));
        items.put(8, item);
        item = new Sprite(materialAtlass.findRegion("mat_wood_zlatolist"));
        items.put(32, item);
        item = new Sprite(materialAtlass.findRegion("mat_metal_cagalyte"));
        items.put(15, item);
        item = new Sprite(materialAtlass.findRegion("mat_skin_kilot"));
        items.put(16, item);
        item = new Sprite(materialAtlass.findRegion("mat_wood_bluetis"));
        items.put(17, item);
        item = new Sprite(materialAtlass.findRegion("mat_alc_zholud"));
        items.put(33, item);
        item = new Sprite(materialAtlass.findRegion("mat_alc_shishka_zlatolist"));
        items.put(34, item);
        item = new Sprite(materialAtlass.findRegion("res_alchemy"));
        items.put(35, item);
        item = new Sprite(materialAtlass.findRegion("mat_alc_cherep_krolika"));
        items.put(36, item);
        item = new Sprite(materialAtlass.findRegion("mat_alc_yagoda_blue"));
        items.put(37, item);
        item = new Sprite(materialAtlass.findRegion("mat_alc_rog_kilota"));
        items.put(38, item);
        item = new Sprite(materialAtlass.findRegion("mat_alc_grib_sin"));
        items.put(39, item);
        item = new Sprite(materialAtlass.findRegion("mat_alc_grib_solnech"));
        items.put(40, item);
        item = new Sprite(materialAtlass.findRegion("mat_alc_snakeskin2"));
        items.put(41, item);
    }

    public static Sprite getItem(int id) {
        return (Sprite)items.get(id);
    }
}

