package ru.megains.farlandsOld.loaders;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.g2d.Sprite;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;

import java.util.HashMap;

public class MobAtlasLoader {
    private static TextureAtlas atlas;
    private static HashMap<Integer, Sprite> mobs;

    public MobAtlasLoader() {
    }

    public static void load() {
        mobs = new HashMap();
        atlas = new TextureAtlas(Gdx.files.internal("mobs/mobs.pack"));
        Sprite mob = new Sprite(atlas.findRegion("arch"));
        mobs.put(Integer.valueOf(1), mob);
        mob = new Sprite(atlas.findRegion("arkan"));
        mobs.put(Integer.valueOf(2), mob);
        mob = new Sprite(atlas.findRegion("arkan2"));
        mobs.put(Integer.valueOf(3), mob);
        mob = new Sprite(atlas.findRegion("arkan3"));
        mobs.put(Integer.valueOf(4), mob);
        mob = new Sprite(atlas.findRegion("boss1"));
        mobs.put(Integer.valueOf(5), mob);
        mob = new Sprite(atlas.findRegion("boss2"));
        mobs.put(Integer.valueOf(6), mob);
        mob = new Sprite(atlas.findRegion("boss3"));
        mobs.put(Integer.valueOf(7), mob);
        mob = new Sprite(atlas.findRegion("butterfly"));
        mobs.put(Integer.valueOf(8), mob);
        mob = new Sprite(atlas.findRegion("chimer"));
        mobs.put(Integer.valueOf(9), mob);
        mob = new Sprite(atlas.findRegion("dragon1"));
        mobs.put(Integer.valueOf(10), mob);
        mob = new Sprite(atlas.findRegion("dragon2"));
        mobs.put(Integer.valueOf(11), mob);
        mob = new Sprite(atlas.findRegion("dragon3"));
        mobs.put(Integer.valueOf(12), mob);
        mob = new Sprite(atlas.findRegion("dragon4"));
        mobs.put(Integer.valueOf(13), mob);
        mob = new Sprite(atlas.findRegion("dragon5"));
        mobs.put(Integer.valueOf(14), mob);
        mob = new Sprite(atlas.findRegion("drak"));
        mobs.put(Integer.valueOf(15), mob);
        mob = new Sprite(atlas.findRegion("drak2"));
        mobs.put(Integer.valueOf(16), mob);
        mob = new Sprite(atlas.findRegion("drak3"));
        mobs.put(Integer.valueOf(17), mob);
        mob = new Sprite(atlas.findRegion("drak4"));
        mobs.put(Integer.valueOf(18), mob);
        mob = new Sprite(atlas.findRegion("dvuhvost"));
        mobs.put(Integer.valueOf(19), mob);
        mob = new Sprite(atlas.findRegion("dvuhvost2"));
        mobs.put(Integer.valueOf(20), mob);
        mob = new Sprite(atlas.findRegion("dvuhvost3"));
        mobs.put(Integer.valueOf(21), mob);
        mob = new Sprite(atlas.findRegion("dvuhvost4"));
        mobs.put(Integer.valueOf(22), mob);
        mob = new Sprite(atlas.findRegion("fober"));
        mobs.put(Integer.valueOf(23), mob);
        mob = new Sprite(atlas.findRegion("guide"));
        mobs.put(Integer.valueOf(24), mob);
        mob = new Sprite(atlas.findRegion("halfarkan"));
        mobs.put(Integer.valueOf(25), mob);
        mob = new Sprite(atlas.findRegion("halfarkan2"));
        mobs.put(Integer.valueOf(26), mob);
        mob = new Sprite(atlas.findRegion("halfarkan3"));
        mobs.put(Integer.valueOf(27), mob);
        mob = new Sprite(atlas.findRegion("hat"));
        mobs.put(Integer.valueOf(28), mob);
        mob = new Sprite(atlas.findRegion("hubitel"));
        mobs.put(Integer.valueOf(29), mob);
        mob = new Sprite(atlas.findRegion("izmornik"));
        mobs.put(Integer.valueOf(30), mob);
        mob = new Sprite(atlas.findRegion("izmornik2"));
        mobs.put(Integer.valueOf(31), mob);
        mob = new Sprite(atlas.findRegion("izmornik3"));
        mobs.put(Integer.valueOf(32), mob);
        mob = new Sprite(atlas.findRegion("izmornik4"));
        mobs.put(Integer.valueOf(33), mob);
        mob = new Sprite(atlas.findRegion("kornevik"));
        mobs.put(Integer.valueOf(34), mob);
        mob = new Sprite(atlas.findRegion("kornevik2"));
        mobs.put(Integer.valueOf(35), mob);
        mob = new Sprite(atlas.findRegion("kornevik3"));
        mobs.put(Integer.valueOf(36), mob);
        mob = new Sprite(atlas.findRegion("krikun"));
        mobs.put(Integer.valueOf(37), mob);
        mob = new Sprite(atlas.findRegion("krikun2"));
        mobs.put(Integer.valueOf(38), mob);
        mob = new Sprite(atlas.findRegion("krikun3"));
        mobs.put(Integer.valueOf(39), mob);
        mob = new Sprite(atlas.findRegion("man01"));
        mobs.put(Integer.valueOf(40), mob);
        mob = new Sprite(atlas.findRegion("melkari"));
        mobs.put(Integer.valueOf(41), mob);
        mob = new Sprite(atlas.findRegion("mon_drac_brown"));
        mobs.put(Integer.valueOf(42), mob);
        mob = new Sprite(atlas.findRegion("mrachnik"));
        mobs.put(Integer.valueOf(43), mob);
        mob = new Sprite(atlas.findRegion("mrachnik2"));
        mobs.put(Integer.valueOf(44), mob);
        mob = new Sprite(atlas.findRegion("mrachnik3"));
        mobs.put(Integer.valueOf(45), mob);
        mob = new Sprite(atlas.findRegion("narlag"));
        mobs.put(Integer.valueOf(46), mob);
        mob = new Sprite(atlas.findRegion("narlag2"));
        mobs.put(Integer.valueOf(47), mob);
        mob = new Sprite(atlas.findRegion("narlag3"));
        mobs.put(Integer.valueOf(48), mob);
        mob = new Sprite(atlas.findRegion("narlag4"));
        mobs.put(Integer.valueOf(49), mob);
        mob = new Sprite(atlas.findRegion("newmobcl1101"));
        mobs.put(Integer.valueOf(50), mob);
        mob = new Sprite(atlas.findRegion("newmobcl1102"));
        mobs.put(Integer.valueOf(51), mob);
        mob = new Sprite(atlas.findRegion("newmobcl1103"));
        mobs.put(Integer.valueOf(52), mob);
        mob = new Sprite(atlas.findRegion("newmobcl1104"));
        mobs.put(Integer.valueOf(53), mob);
        mob = new Sprite(atlas.findRegion("newmobcl1105"));
        mobs.put(Integer.valueOf(54), mob);
        mob = new Sprite(atlas.findRegion("neyav"));
        mobs.put(Integer.valueOf(55), mob);
        mob = new Sprite(atlas.findRegion("neyav06"));
        mobs.put(Integer.valueOf(60), mob);
        mob = new Sprite(atlas.findRegion("neyav07"));
        mobs.put(Integer.valueOf(61), mob);
        mob = new Sprite(atlas.findRegion("neyav08"));
        mobs.put(Integer.valueOf(62), mob);
        mob = new Sprite(atlas.findRegion("neyav09"));
        mobs.put(Integer.valueOf(63), mob);
        mob = new Sprite(atlas.findRegion("neyav2"));
        mobs.put(Integer.valueOf(56), mob);
        mob = new Sprite(atlas.findRegion("neyav3"));
        mobs.put(Integer.valueOf(57), mob);
        mob = new Sprite(atlas.findRegion("neyav4"));
        mobs.put(Integer.valueOf(58), mob);
        mob = new Sprite(atlas.findRegion("neyav5"));
        mobs.put(Integer.valueOf(59), mob);
        mob = new Sprite(atlas.findRegion("phantom"));
        mobs.put(Integer.valueOf(64), mob);
        mob = new Sprite(atlas.findRegion("pilevik"));
        mobs.put(Integer.valueOf(65), mob);
        mob = new Sprite(atlas.findRegion("pilevik2"));
        mobs.put(Integer.valueOf(66), mob);
        mob = new Sprite(atlas.findRegion("pilevik3"));
        mobs.put(Integer.valueOf(67), mob);
        mob = new Sprite(atlas.findRegion("pilevik4"));
        mobs.put(Integer.valueOf(68), mob);
        mob = new Sprite(atlas.findRegion("potroshitel"));
        mobs.put(Integer.valueOf(69), mob);
        mob = new Sprite(atlas.findRegion("potroshitel2"));
        mobs.put(Integer.valueOf(70), mob);
        mob = new Sprite(atlas.findRegion("potroshitel3"));
        mobs.put(Integer.valueOf(71), mob);
        mob = new Sprite(atlas.findRegion("pozhiratel"));
        mobs.put(Integer.valueOf(72), mob);
        mob = new Sprite(atlas.findRegion("pozhiratel2"));
        mobs.put(Integer.valueOf(73), mob);
        mob = new Sprite(atlas.findRegion("pozhiratel3"));
        mobs.put(Integer.valueOf(74), mob);
        mob = new Sprite(atlas.findRegion("prigun"));
        mobs.put(Integer.valueOf(75), mob);
        mob = new Sprite(atlas.findRegion("prigun2"));
        mobs.put(Integer.valueOf(76), mob);
        mob = new Sprite(atlas.findRegion("prigun3"));
        mobs.put(Integer.valueOf(77), mob);
        mob = new Sprite(atlas.findRegion("pustotnik"));
        mobs.put(Integer.valueOf(78), mob);
        mob = new Sprite(atlas.findRegion("pustotnik2"));
        mobs.put(Integer.valueOf(79), mob);
        mob = new Sprite(atlas.findRegion("pustotnik3"));
        mobs.put(Integer.valueOf(80), mob);
        mob = new Sprite(atlas.findRegion("rvach"));
        mobs.put(Integer.valueOf(81), mob);
        mob = new Sprite(atlas.findRegion("rvach2"));
        mobs.put(Integer.valueOf(82), mob);
        mob = new Sprite(atlas.findRegion("rvach3"));
        mobs.put(Integer.valueOf(83), mob);
        mob = new Sprite(atlas.findRegion("shestinog"));
        mobs.put(Integer.valueOf(84), mob);
        mob = new Sprite(atlas.findRegion("shestinog2"));
        mobs.put(Integer.valueOf(85), mob);
        mob = new Sprite(atlas.findRegion("shestinog3"));
        mobs.put(Integer.valueOf(86), mob);
        mob = new Sprite(atlas.findRegion("snake"));
        mobs.put(Integer.valueOf(87), mob);
        mob = new Sprite(atlas.findRegion("tord"));
        mobs.put(Integer.valueOf(88), mob);
        mob = new Sprite(atlas.findRegion("unic1_arch"));
        mobs.put(Integer.valueOf(89), mob);
        mob = new Sprite(atlas.findRegion("unic1_arkan"));
        mobs.put(Integer.valueOf(90), mob);
        mob = new Sprite(atlas.findRegion("unic1_boss1"));
        mobs.put(Integer.valueOf(91), mob);
        mob = new Sprite(atlas.findRegion("unic1_boss2"));
        mobs.put(Integer.valueOf(92), mob);
        mob = new Sprite(atlas.findRegion("unic1_boss3"));
        mobs.put(Integer.valueOf(93), mob);
        mob = new Sprite(atlas.findRegion("unic1_chimer"));
        mobs.put(Integer.valueOf(94), mob);
        mob = new Sprite(atlas.findRegion("unic1_drak"));
        mobs.put(Integer.valueOf(95), mob);
        mob = new Sprite(atlas.findRegion("unic1_dvuhvost"));
        mobs.put(Integer.valueOf(96), mob);
        mob = new Sprite(atlas.findRegion("unic1_fober"));
        mobs.put(Integer.valueOf(97), mob);
        mob = new Sprite(atlas.findRegion("unic1_halfarkan"));
        mobs.put(Integer.valueOf(98), mob);
        mob = new Sprite(atlas.findRegion("unic1_izmornik"));
        mobs.put(Integer.valueOf(99), mob);
        mob = new Sprite(atlas.findRegion("unic1_kornevik"));
        mobs.put(Integer.valueOf(100), mob);
        mob = new Sprite(atlas.findRegion("unic1_krikun"));
        mobs.put(Integer.valueOf(101), mob);
        mob = new Sprite(atlas.findRegion("unic1_melkari"));
        mobs.put(Integer.valueOf(102), mob);
        mob = new Sprite(atlas.findRegion("izmornik"));
        mobs.put(Integer.valueOf(103), mob);
        mob = new Sprite(atlas.findRegion("unic1_mrachnik"));
        mobs.put(Integer.valueOf(104), mob);
        mob = new Sprite(atlas.findRegion("unic1_neyav"));
        mobs.put(Integer.valueOf(105), mob);
        mob = new Sprite(atlas.findRegion("unic1_pilevik"));
        mobs.put(Integer.valueOf(106), mob);
        mob = new Sprite(atlas.findRegion("unic1_potroshitel"));
        mobs.put(Integer.valueOf(107), mob);
        mob = new Sprite(atlas.findRegion("unic1_pozhiratel"));
        mobs.put(Integer.valueOf(108), mob);
        mob = new Sprite(atlas.findRegion("unic1_prigun"));
        mobs.put(Integer.valueOf(109), mob);
        mob = new Sprite(atlas.findRegion("unic1_pustotnik"));
        mobs.put(Integer.valueOf(110), mob);
        mob = new Sprite(atlas.findRegion("unic1_rvach"));
        mobs.put(Integer.valueOf(111), mob);
        mob = new Sprite(atlas.findRegion("unic1_shestinog"));
        mobs.put(Integer.valueOf(112), mob);
        mob = new Sprite(atlas.findRegion("unic1_tord"));
        mobs.put(Integer.valueOf(113), mob);
        mob = new Sprite(atlas.findRegion("unic1_yascher"));
        mobs.put(Integer.valueOf(114), mob);
        mob = new Sprite(atlas.findRegion("unic1_zmei"));
        mobs.put(Integer.valueOf(115), mob);
        mob = new Sprite(atlas.findRegion("yascher"));
        mobs.put(Integer.valueOf(116), mob);
        mob = new Sprite(atlas.findRegion("yascher2"));
        mobs.put(Integer.valueOf(117), mob);
        mob = new Sprite(atlas.findRegion("yascher3"));
        mobs.put(Integer.valueOf(118), mob);
        mob = new Sprite(atlas.findRegion("yascher4"));
        mobs.put(Integer.valueOf(119), mob);
        mob = new Sprite(atlas.findRegion("zmei"));
        mobs.put(Integer.valueOf(120), mob);
        mob = new Sprite(atlas.findRegion("zmei2"));
        mobs.put(Integer.valueOf(121), mob);
        mob = new Sprite(atlas.findRegion("zmei3"));
        mobs.put(Integer.valueOf(122), mob);
        mob = new Sprite(atlas.findRegion("zmei4"));
        mobs.put(Integer.valueOf(123), mob);
    }

    public static Sprite getSpriteById(int id) {
        return (Sprite)mobs.get(id);
    }
}
